
#4 elts principale apiVersion ,kind(pod [[restart auto ]], Replicaset[[si node down replicat auto sur une autre node]],Deploiment[[]]),metadata[[dictionaire ]],spec[[specification:template of containers]]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    type: rs
spec:
  replicas: 7
  template:
    metadata:
      name: my-pod
      labels:
        type: webserver
    spec:
        containers:
        - name: crud-container
          image: mohamedamineblibech/crudapp:1.1.1
          ports:
            - name: crud-container
              containerPort: 3000
              targetPort: 80
#gere les objet nouvellement cree 
  selector:
    matchLabels:
      type: reactnode 
      
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
#port of container inside pod
  - targetPort: 3000
#port de service prend flux 3000 redirection vers port du pod
    port: 80
#port phy 3ibaratan map 3000 redirger vers port du service 80
    nodePort: 30000
#ya3ref les pods ili na7ki a3lihom ->label pod
  selector:
    type: reactnode



